using System;
using System.Collections.Concurrent;
using System.IO;
using FleetPulse.Enums;
using FleetPulse.Exceptions;
using FleetPulse.Models;
using FleetPulse.Services;
using FleetPulse.UI;

namespace FleetPulse
{
    /// <summary>
    /// The main entry point for the FleetPulse application.
    /// Handles the application lifecycle, background monitoring, and the main user interface loop.
    /// </summary>
    public static class Program
    {
        // Central hub for managing vehicles, drivers, and routes.
        private static readonly DispatchCenter Dispatch = new();
        
        // Random.Shared is thread-safe (unlike new Random()) which is safer for concurrent environments.
        private static readonly Random Rng = Random.Shared; 
        
        // Default file path for persisting application state.
        private const string SaveFilePath = "fleetpulse_state.json";

        // A thread-safe queue to capture events generated by background monitoring threads.
        // This prevents cross-thread console writing collisions.
        private static readonly ConcurrentQueue<(ConsoleColor color, string tag, string message)> EventLogs = new();

        public static void Main(string[] args)
        {
            // 1. Setup event listeners for background dispatch activities
            SubscribeToEvents();
            
            // 2. Populate the system with initial mock data
            SeedRandomData();
            
            // 3. Start background threads that check for fuel, breakdowns, and deliveries
            Dispatch.StartMonitoring();

            string startupMsg = "Background monitoring started (fuel, breakdowns, maintenance, auto-deliveries).\n";
            
            // 4. Enter the primary interactive console loop
            RunMenu(startupMsg);

            // 5. Clean up and shut down gracefully once the user exits the menu
            Dispatch.StopMonitoring();
            Console.Clear();
            MenuRender.PrintSuccess("Shutting down FleetPulse. Goodbye!");
        }

        // ---------------- Console Helper Methods ----------------

        /// <summary>
        /// Hooks into the DispatchCenter's events to log system occurrences.
        /// </summary>
        private static void SubscribeToEvents()
        {
            // Register delegates to handle different system events, assigning them specific colors and tags
            Dispatch.BreakdownDetected += (v, msg) => LogEvent(ConsoleColor.Red, "BREAKDOWN", msg);
            Dispatch.FuelLowWarning += (v, msg) => LogEvent(ConsoleColor.Yellow, "FUEL LOW", msg);
            Dispatch.MaintenanceDue += (v, msg) => LogEvent(ConsoleColor.Magenta, "MAINTENANCE", msg);
            Dispatch.DeliveryCompleted += route =>
                LogEvent(ConsoleColor.Green, "DELIVERED",
                    $"Route#{route.RouteId} ({route.Origin} -> {route.Destination}) completed.");
        }

        /// <summary>
        /// Pushes a new log entry into the thread-safe queue instead of writing directly to the console.
        /// </summary>
        private static void LogEvent(ConsoleColor color, string tag, string message)
        {
            EventLogs.Enqueue((color, tag, message));
        }

        /// <summary>
        /// Empties the background event queue and prints all pending logs to the console safely.
        /// </summary>
        public static void FlushLogs()
        {
            bool hasLogs = false;
            
            // Dequeue items until the queue is empty
            while (EventLogs.TryDequeue(out var log))
            {
                // Temporarily change console color for the specific log type, then restore it
                var prev = Console.ForegroundColor;
                Console.ForegroundColor = log.color;
                Console.WriteLine($"[{DateTime.Now:HH:mm:ss}] [{log.tag}] {log.message}");
                Console.ForegroundColor = prev;
                hasLogs = true;
            }

            // Add a visual spacer if any logs were printed
            if (hasLogs)
            {
                Console.WriteLine(); 
            }
        }

        /// <summary>
        /// Populates the dispatch center with dummy vehicles, drivers, and routes for testing.
        /// </summary>
        private static void SeedRandomData()
        {
            // Add varied vehicle types
            Dispatch.AddVehicle(new Truck($"TRK-{Rng.Next(100, 999)}", Rng.Next(3000, 12000)));
            Dispatch.AddVehicle(new Van($"VAN-{Rng.Next(100, 999)}", Rng.Next(20, 80)));
            Dispatch.AddVehicle(new Bus($"BUS-{Rng.Next(100, 999)}", Rng.Next(30, 60)));

            // Add drivers with specific license classes
            Dispatch.AddDriver(new Driver("Thabo Nkosi", "C1-EL"));
            Dispatch.AddDriver(new Driver("Amanda van Wyk", "EC1"));

            // Generate 3 random routes using preset locations
            for (int i = 0; i < 3; i++)
            {
                string origin = RouteUI.PresetPlaces[Rng.Next(RouteUI.PresetPlaces.Length)];
                string dest;
                
                // Ensure the destination is different from the origin
                do
                {
                    dest = RouteUI.PresetPlaces[Rng.Next(RouteUI.PresetPlaces.Length)];
                } while (dest == origin);

                var priority = (Priority)Rng.Next(0, 4);
                Dispatch.CreateRoute(origin, dest, Rng.Next(50, 600), priority);
            }
        }

        // ---------------- Menu loop ----------------

        /// <summary>
        /// The main UI loop that keeps the application running until the user selects 'Exit'.
        /// </summary>
        private static void RunMenu(string? startupMessage = null)
        {
            bool running = true;
            string? currentMsg = startupMessage;
            string? errorMsg = null;

            while (running)
            {
                Console.Clear();
                
                // [FIXED]: Print any background events that occurred while the user was in a menu
                FlushLogs();
                
                // Render the main menu options, including any success/error messages from the previous action
                MenuRender.PrintMenu(currentMsg, errorMsg);
                
                // Clear messages so they don't persist on the next loop iteration
                currentMsg = null;
                errorMsg = null;

                string? choice = Console.ReadLine();

                try
                {
                    // Attempt to parse the user's input into the MainMenuOption enum
                    if (Enum.TryParse(choice, out MainMenuOption menuOption) && Enum.IsDefined(menuOption))
                    {
                        // Clear screen and show a header for the selected sub-menu (unless exiting)
                        if (menuOption != MainMenuOption.Exit)
                        {
                            Console.Clear();
                            MenuRender.MenuHeader();
                        }

                        // Route the application to the correct UI flow based on user choice
                        switch (menuOption)
                        {
                            case MainMenuOption.ViewFleet:
                                VehicleUI.ViewFleet(Dispatch);
                                break;
                            case MainMenuOption.AddVehicle:
                                (currentMsg, errorMsg) = VehicleUI.AddVehicleFlow(Dispatch);
                                break;
                            case MainMenuOption.RemoveVehicle:
                                (currentMsg, errorMsg) = VehicleUI.RemoveVehicleFlow(Dispatch);
                                break;
                            case MainMenuOption.AddDriver:
                                (currentMsg, errorMsg) = DriverUI.AddDriverFlow(Dispatch);
                                break;
                            case MainMenuOption.CreateRoute:
                                (currentMsg, errorMsg) = RouteUI.CreateRouteFlow(Dispatch, RouteUI.PresetPlaces);
                                break;
                            case MainMenuOption.AssignRoute:
                                (currentMsg, errorMsg) = RouteUI.AssignRouteFlow(Dispatch);
                                break;
                            case MainMenuOption.ViewRoutes:
                                RouteUI.ViewRoutes(Dispatch);
                                break;
                            case MainMenuOption.ViewReports:
                                RouteUI.ViewReports(Dispatch);
                                break;
                            case MainMenuOption.SaveState:
                                (currentMsg, errorMsg) = SaveStateFlow();
                                break;
                            case MainMenuOption.LoadState:
                                (currentMsg, errorMsg) = LoadStateFlow();
                                break;
                            case MainMenuOption.ToggleMonitoring:
                                (currentMsg, errorMsg) = ToggleMonitoring();
                                break;
                            case MainMenuOption.ViewDrivers:
                                DriverUI.ViewDrivers(Dispatch);
                                break;
                            case MainMenuOption.Exit:
                                running = false; // Breaks the while loop
                                break;
                        }
                    }
                    else
                    {
                        errorMsg = "Invalid option, please choose again.\n";
                    }
                }
                // Domain-specific exception handling ensures the app doesn't crash on business logic errors
                catch (FleetCapacityExceededException ex)
                {
                    errorMsg = $"[Capacity Error] {ex.Message}\n";
                }
                catch (DriverHourLimitExceededException ex)
                {
                    errorMsg = $"[Driver Hours Error] {ex.Message}\n";
                }
                catch (InvalidRouteAssignmentException ex)
                {
                    errorMsg = $"[Assignment Error] {ex.Message}\n";
                }
                catch (FileNotFoundException ex)
                {
                    errorMsg = $"[File Error] {ex.Message}\n";
                }
                catch (FormatException)
                {
                    errorMsg = "[Input Error] Please enter a valid number where a number is expected.\n";
                }
                catch (Exception ex)
                {
                    // Catch-all for unexpected issues to prevent a hard crash
                    errorMsg = $"[Unexpected Error] {ex.Message}\n";
                }
            }
        }

        // ---------------- Menu actions ----------------

        /// <summary>
        /// Serializes current state to a JSON file.
        /// </summary>
        private static (string? success, string? error) SaveStateFlow()
        {
            // [FIXED]: Temporarily halt background monitoring to avoid race conditions while reading data for serialization
            bool wasMonitoring = Dispatch.IsMonitoring;
            if (wasMonitoring) Dispatch.StopMonitoring();

            try
            {
                FileManager.SaveState(SaveFilePath, Dispatch.Fleet, Dispatch.Drivers);
                return ($"State saved to {SaveFilePath}.\n", null);
            }
            finally
            {
                // Resume monitoring if it was active beforehand
                if (wasMonitoring) Dispatch.StartMonitoring();
            }
        }

        /// <summary>
        /// Deserializes state from a JSON file and overwrites the current session.
        /// </summary>
        private static (string? success, string? error) LoadStateFlow()
        {
            var snapshot = FileManager.LoadState(SaveFilePath);
            Dispatch.LoadFromSnapshot(snapshot);
            return ($"State loaded from {SaveFilePath} (saved at {snapshot.SavedAt}).\n", null);
        }

        /// <summary>
        /// Starts or stops the background threads simulating real-time events.
        /// </summary>
        private static (string? success, string? error) ToggleMonitoring()
        {
            if (Dispatch.IsMonitoring)
            {
                Dispatch.StopMonitoring();
                return ("Background monitoring stopped.\n", null);
            }
            else
            {
                Dispatch.StartMonitoring();
                return ("Background monitoring started.\n", null);
            }
        }
    }
}